### ISSUE TITLE
Generated DAG survey link changes when updating REDCap version

### ISSUE THREAD

**Issue by harpsicord86** [susom/redcap-em-public-survey-dag#5]
Hi @123andy 

I've found what may be a slight 'flaw' in the way your module creates URLs. At the moment, the module includes the version number of the REDCap installation within its generated URL. This does change in line with if the REDCap installation is upgraded, however, we've been using the REDCap URL shortener service to send out as an easy-to-read link and because we've had to upgrade REDCap recently, it has meant that the URL breaks as a result.

Is there any way of removing the version number from the generated URL going forward?

**Comment by 123andy** [comment]
This is a general issue across all of Redcap.   Many users undoubtedly bookmark version urls as well.  Our solution for this is here:

https://github.com/susom/redcap-redirect

It has been adopted by many sites over the years.
________________________________
From: Steve Harper ***@***.***>
Sent: Tuesday, May 9, 2023 6:22:04 AM
To: susom/redcap-em-public-survey-dag ***@***.***>
Cc: Andy Martin ***@***.***>; Mention ***@***.***>
Subject: [susom/redcap-em-public-survey-dag] Generated DAG survey link changes when updating REDCap version (Issue #5)


Hi @123andy<https://github.com/123andy>

I've found what may be a slight 'flaw' in the way your module creates URLs. At the moment, the module includes the version number of the REDCap installation within its generated URL. This does change in line with if the REDCap installation is upgraded, however, we've been using the REDCap URL shortener service to send out as an easy-to-read link and because we've had to upgrade REDCap recently, it has meant that the URL breaks as a result.

Is there any way of removing the version number from the generated URL going forward?

**Comment by harpsicord86** [comment]
Thanks @123andy 

Unfortunately, my REDCap environment is built within nginx. We would need to rework your solution to work with nginx instead of apache. Thanks anyway

**Comment by 123andy** [comment]
@harpsicord86 - there is another solution which is to goto the Control Center / Manage External Modules / and in the 'System-level' settings for this EM, tell it to use the API-based urls instead.  These do not have the version number in them, and, provided your institution does not block the API urls from public networks it should work.  This will not, hoever, fix existing urls that may have been provided.

![image](https://github.com/susom/redcap-em-public-survey-dag/assets/7461553/6bacf5ed-1ae0-4d81-be30-cb3006b424d4)

I should also add that I'm sure it is pretty trivial to rework my solution for nginx.  Reach out on the consortium for help if you're unable to figure it out on your own.
